#!/usr/bin/env bash
#install Nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw "Nginx HTTP"
echo "Hello world!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx reload
